### ISSUE TITLE
Missing test for routine is_valid_account_number in class ACCOUNT_NUMBER

### ISSUE THREAD

**Issue by nricci** [nmaguirre/eiffel-bank-ocr#27]
Provide appropriate test/s for the routine.

**Comment by jicibils** [comment]
Resolved in rev. 849f542

**Comment by nmaguirre** [comment]
Please notice that you are not using the class' API correctly. Routine set_account_number_from_string_rep takes string representations of the kind "|_ |_ ...", i.e., with numbers made out of pipes, underscores and blank spaces. Please use set_account_number instead. I'm removing the "resolved" tag. Thanks!

**Comment by jicibils** [comment]
Resolved in rev. 3fb6af7

**Comment by nmaguirre** [comment]
Well done! Thanks!

**Comment by jicibils** [comment]
Resolved in rev. 76f0689

**Comment by nmaguirre** [comment]
Notice that you are using constants True and False. These should have the first letter in capital. Also, one of the descriptions of the assert is inconsistent with what is being checked. Please check these problems and solve them. I'm removing the resolved tag.

**Comment by jicibils** [comment]
Resolved in rev. 3338c08

**Comment by rdegiovanni** [comment]
Your test has an incorrect comment.
-- for example: number account= "987654321"
-- sum = (9_10)+(8_100)+(7_1000)+...+(1_1000000000)

Notice that, for example, you have to multiply 9 by 1000000000 because it is the most representative number, and so on. 
Check now if your test is correct, and either, fix it or report the bug to whom implemented the is_valid_account_number routine of class ACCOUNT_NUMBER.

**Comment by jicibils** [comment]
Resolved in rev. 741c957

**Comment by jicibils** [comment]
Resolved in rev. 586ba85

**Comment by nmaguirre** [comment]
Well done! Thanks!
