### ISSUE TITLE
Missing Implementation for routine ACCOUNT_NUMBER.set_account_number

### ISSUE THREAD

**Issue by miri15** [nmaguirre/eiffel-bank-ocr#35]

**Comment by miri15** [comment]
solved in rev. 53bb418

**Comment by nmaguirre** [comment]
Well done! Thanks!

**Comment by lukax77** [comment]
There's a bug in your implementation, the index interval for number array is 1 to 9, and your index i starts from 0. Furthermore you create a single object ACCOUNT_DIGIT thus the array has the same digit in each position, you should create the object in the cycle so that each iteration have a different ACCOUNT_DIGIT object for each array position.

**Comment by miri15** [comment]
Bug fixed. Solved in rev 433691e

**Comment by ibongiovanni** [comment]
the previous exit condition (i > 9) was correct, the current (i > 10) is not, in any case, it could be i >= 10

**Comment by miri15** [comment]
You are right. Bug fixed in rev 3ce0d3f
